# Generated by Django 5.2.6 on 2025-09-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='project',
            name='expected_launch',
            field=models.DateField(blank=True, help_text='For coming soon projects', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('data-analysis', 'Data Analysis'), ('web-development', 'Web Development'), ('data-visualization', 'Data Visualization'), ('machine-learning', 'Machine Learning'), ('coming-soon', 'Coming Soon')], default='web-development', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress'), ('planning', 'Planning'), ('coming-soon', 'Coming Soon')], default='completed', max_length=20),
        ),
    ]
