# Generated by Django 5.2.6 on 2025-09-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_options_project_expected_launch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('data-analytics', 'Data Analytics'), ('web-development', 'Web Development'), ('machine-learning', 'Machine Learning / AI'), ('coming-soon', 'Coming Soon')], default='web-development', max_length=20),
        ),
    ]
