# Generated by Django 5.2.6 on 2025-09-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('data-analytics', 'Data Analytics'), ('web-development', 'Web Development'), ('python-gui', 'Python GUI'), ('machine-learning', 'Machine Learning'), ('coming-soon', 'Coming Soon')], default='web-development', max_length=20),
        ),
    ]
