# Generated by Django 5.2.6 on 2025-09-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='language',
            name='accent',
            field=models.CharField(blank=True, help_text='e.g., American English, British English', max_length=100),
        ),
        migrations.AddField(
            model_name='language',
            name='accents',
            field=models.TextField(blank=True, help_text='Comma-separated list of accents/variants'),
        ),
        migrations.AddField(
            model_name='language',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='language_certificates/'),
        ),
        migrations.AddField(
            model_name='language',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='language_flags/'),
        ),
        migrations.AddField(
            model_name='language',
            name='listening_proficiency',
            field=models.CharField(choices=[('native', 'Native / Fluent'), ('professional', 'Professional'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('basic', 'Basic'), ('beginner', 'Beginner')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='reading_proficiency',
            field=models.CharField(choices=[('native', 'Native / Fluent'), ('professional', 'Professional'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('basic', 'Basic'), ('beginner', 'Beginner')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='speaking_proficiency',
            field=models.CharField(choices=[('native', 'Native / Fluent'), ('professional', 'Professional'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('basic', 'Basic'), ('beginner', 'Beginner')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='writing_proficiency',
            field=models.CharField(choices=[('native', 'Native / Fluent'), ('professional', 'Professional'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('basic', 'Basic'), ('beginner', 'Beginner')], default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='audio_sample',
            field=models.FileField(blank=True, null=True, upload_to='language_samples/'),
        ),
    ]
