# Generated by Django 5.2.6 on 2025-10-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_language_proficiency_language_accent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, help_text='City, Country', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, help_text='City, Country', max_length=100),
        ),
    ]
